/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MobileRouteRouteImport } from './routes/mobile/route'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as MobileAuthenticatedRouteImport } from './routes/mobile/_authenticated'
import { Route as WebAuthenticatedRouteImport } from './routes/_web/_authenticated'
import { Route as MobileAuthenticatedDashboardRouteImport } from './routes/mobile/_authenticated/dashboard'
import { Route as MobileAuthenticatedCalendarRouteImport } from './routes/mobile/_authenticated/calendar'
import { Route as MobileAuthenticatedBookingsRouteImport } from './routes/mobile/_authenticated/bookings'
import { Route as WebAuthenticatedDashboardRouteImport } from './routes/_web/_authenticated/dashboard'
import { Route as WebAuthenticatedCalendarRouteImport } from './routes/_web/_authenticated/calendar'
import { Route as WebAuthenticatedBookingsRouteImport } from './routes/_web/_authenticated/bookings'
import { Route as MobileAuthenticatedCustomersIndexRouteImport } from './routes/mobile/_authenticated/customers/index'
import { Route as WebAuthenticatedCustomersIndexRouteImport } from './routes/_web/_authenticated/customers.index'
import { Route as MobileAuthenticatedCustomersIdRouteImport } from './routes/mobile/_authenticated/customers/$id'
import { Route as WebAuthenticatedCustomersIdRouteImport } from './routes/_web/_authenticated/customers.$id'

const MobileRouteRoute = MobileRouteRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRouteRoute,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/_web/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAuthenticatedRoute = MobileAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MobileRouteRoute,
} as any)
const WebAuthenticatedRoute = WebAuthenticatedRouteImport.update({
  id: '/_web/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAuthenticatedDashboardRoute =
  MobileAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => MobileAuthenticatedRoute,
  } as any)
const MobileAuthenticatedCalendarRoute =
  MobileAuthenticatedCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => MobileAuthenticatedRoute,
  } as any)
const MobileAuthenticatedBookingsRoute =
  MobileAuthenticatedBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => MobileAuthenticatedRoute,
  } as any)
const WebAuthenticatedDashboardRoute =
  WebAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => WebAuthenticatedRoute,
  } as any)
const WebAuthenticatedCalendarRoute =
  WebAuthenticatedCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => WebAuthenticatedRoute,
  } as any)
const WebAuthenticatedBookingsRoute =
  WebAuthenticatedBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => WebAuthenticatedRoute,
  } as any)
const MobileAuthenticatedCustomersIndexRoute =
  MobileAuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => MobileAuthenticatedRoute,
  } as any)
const WebAuthenticatedCustomersIndexRoute =
  WebAuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => WebAuthenticatedRoute,
  } as any)
const MobileAuthenticatedCustomersIdRoute =
  MobileAuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => MobileAuthenticatedRoute,
  } as any)
const WebAuthenticatedCustomersIdRoute =
  WebAuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => WebAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/mobile': typeof MobileRouteRouteWithChildren
  '/': typeof WebIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/bookings': typeof WebAuthenticatedBookingsRoute
  '/calendar': typeof WebAuthenticatedCalendarRoute
  '/dashboard': typeof WebAuthenticatedDashboardRoute
  '/mobile/bookings': typeof MobileAuthenticatedBookingsRoute
  '/mobile/calendar': typeof MobileAuthenticatedCalendarRoute
  '/mobile/dashboard': typeof MobileAuthenticatedDashboardRoute
  '/customers/$id': typeof WebAuthenticatedCustomersIdRoute
  '/mobile/customers/$id': typeof MobileAuthenticatedCustomersIdRoute
  '/customers/': typeof WebAuthenticatedCustomersIndexRoute
  '/mobile/customers/': typeof MobileAuthenticatedCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WebIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/bookings': typeof WebAuthenticatedBookingsRoute
  '/calendar': typeof WebAuthenticatedCalendarRoute
  '/dashboard': typeof WebAuthenticatedDashboardRoute
  '/mobile/bookings': typeof MobileAuthenticatedBookingsRoute
  '/mobile/calendar': typeof MobileAuthenticatedCalendarRoute
  '/mobile/dashboard': typeof MobileAuthenticatedDashboardRoute
  '/customers/$id': typeof WebAuthenticatedCustomersIdRoute
  '/mobile/customers/$id': typeof MobileAuthenticatedCustomersIdRoute
  '/customers': typeof WebAuthenticatedCustomersIndexRoute
  '/mobile/customers': typeof MobileAuthenticatedCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/mobile': typeof MobileRouteRouteWithChildren
  '/_web/_authenticated': typeof WebAuthenticatedRouteWithChildren
  '/mobile/_authenticated': typeof MobileAuthenticatedRouteWithChildren
  '/_web/': typeof WebIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/_web/_authenticated/bookings': typeof WebAuthenticatedBookingsRoute
  '/_web/_authenticated/calendar': typeof WebAuthenticatedCalendarRoute
  '/_web/_authenticated/dashboard': typeof WebAuthenticatedDashboardRoute
  '/mobile/_authenticated/bookings': typeof MobileAuthenticatedBookingsRoute
  '/mobile/_authenticated/calendar': typeof MobileAuthenticatedCalendarRoute
  '/mobile/_authenticated/dashboard': typeof MobileAuthenticatedDashboardRoute
  '/_web/_authenticated/customers/$id': typeof WebAuthenticatedCustomersIdRoute
  '/mobile/_authenticated/customers/$id': typeof MobileAuthenticatedCustomersIdRoute
  '/_web/_authenticated/customers/': typeof WebAuthenticatedCustomersIndexRoute
  '/mobile/_authenticated/customers/': typeof MobileAuthenticatedCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/mobile'
    | '/'
    | '/mobile/'
    | '/bookings'
    | '/calendar'
    | '/dashboard'
    | '/mobile/bookings'
    | '/mobile/calendar'
    | '/mobile/dashboard'
    | '/customers/$id'
    | '/mobile/customers/$id'
    | '/customers/'
    | '/mobile/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mobile'
    | '/bookings'
    | '/calendar'
    | '/dashboard'
    | '/mobile/bookings'
    | '/mobile/calendar'
    | '/mobile/dashboard'
    | '/customers/$id'
    | '/mobile/customers/$id'
    | '/customers'
    | '/mobile/customers'
  id:
    | '__root__'
    | '/mobile'
    | '/_web/_authenticated'
    | '/mobile/_authenticated'
    | '/_web/'
    | '/mobile/'
    | '/_web/_authenticated/bookings'
    | '/_web/_authenticated/calendar'
    | '/_web/_authenticated/dashboard'
    | '/mobile/_authenticated/bookings'
    | '/mobile/_authenticated/calendar'
    | '/mobile/_authenticated/dashboard'
    | '/_web/_authenticated/customers/$id'
    | '/mobile/_authenticated/customers/$id'
    | '/_web/_authenticated/customers/'
    | '/mobile/_authenticated/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MobileRouteRoute: typeof MobileRouteRouteWithChildren
  WebAuthenticatedRoute: typeof WebAuthenticatedRouteWithChildren
  WebIndexRoute: typeof WebIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRouteRoute
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/_authenticated': {
      id: '/mobile/_authenticated'
      path: ''
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileAuthenticatedRouteImport
      parentRoute: typeof MobileRouteRoute
    }
    '/_web/_authenticated': {
      id: '/_web/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/_authenticated/dashboard': {
      id: '/mobile/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/mobile/dashboard'
      preLoaderRoute: typeof MobileAuthenticatedDashboardRouteImport
      parentRoute: typeof MobileAuthenticatedRoute
    }
    '/mobile/_authenticated/calendar': {
      id: '/mobile/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/mobile/calendar'
      preLoaderRoute: typeof MobileAuthenticatedCalendarRouteImport
      parentRoute: typeof MobileAuthenticatedRoute
    }
    '/mobile/_authenticated/bookings': {
      id: '/mobile/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/mobile/bookings'
      preLoaderRoute: typeof MobileAuthenticatedBookingsRouteImport
      parentRoute: typeof MobileAuthenticatedRoute
    }
    '/_web/_authenticated/dashboard': {
      id: '/_web/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WebAuthenticatedDashboardRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
    '/_web/_authenticated/calendar': {
      id: '/_web/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof WebAuthenticatedCalendarRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
    '/_web/_authenticated/bookings': {
      id: '/_web/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof WebAuthenticatedBookingsRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
    '/mobile/_authenticated/customers/': {
      id: '/mobile/_authenticated/customers/'
      path: '/customers'
      fullPath: '/mobile/customers/'
      preLoaderRoute: typeof MobileAuthenticatedCustomersIndexRouteImport
      parentRoute: typeof MobileAuthenticatedRoute
    }
    '/_web/_authenticated/customers/': {
      id: '/_web/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof WebAuthenticatedCustomersIndexRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
    '/mobile/_authenticated/customers/$id': {
      id: '/mobile/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/mobile/customers/$id'
      preLoaderRoute: typeof MobileAuthenticatedCustomersIdRouteImport
      parentRoute: typeof MobileAuthenticatedRoute
    }
    '/_web/_authenticated/customers/$id': {
      id: '/_web/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof WebAuthenticatedCustomersIdRouteImport
      parentRoute: typeof WebAuthenticatedRoute
    }
  }
}

interface MobileAuthenticatedRouteChildren {
  MobileAuthenticatedBookingsRoute: typeof MobileAuthenticatedBookingsRoute
  MobileAuthenticatedCalendarRoute: typeof MobileAuthenticatedCalendarRoute
  MobileAuthenticatedDashboardRoute: typeof MobileAuthenticatedDashboardRoute
  MobileAuthenticatedCustomersIdRoute: typeof MobileAuthenticatedCustomersIdRoute
  MobileAuthenticatedCustomersIndexRoute: typeof MobileAuthenticatedCustomersIndexRoute
}

const MobileAuthenticatedRouteChildren: MobileAuthenticatedRouteChildren = {
  MobileAuthenticatedBookingsRoute: MobileAuthenticatedBookingsRoute,
  MobileAuthenticatedCalendarRoute: MobileAuthenticatedCalendarRoute,
  MobileAuthenticatedDashboardRoute: MobileAuthenticatedDashboardRoute,
  MobileAuthenticatedCustomersIdRoute: MobileAuthenticatedCustomersIdRoute,
  MobileAuthenticatedCustomersIndexRoute:
    MobileAuthenticatedCustomersIndexRoute,
}

const MobileAuthenticatedRouteWithChildren =
  MobileAuthenticatedRoute._addFileChildren(MobileAuthenticatedRouteChildren)

interface MobileRouteRouteChildren {
  MobileAuthenticatedRoute: typeof MobileAuthenticatedRouteWithChildren
  MobileIndexRoute: typeof MobileIndexRoute
}

const MobileRouteRouteChildren: MobileRouteRouteChildren = {
  MobileAuthenticatedRoute: MobileAuthenticatedRouteWithChildren,
  MobileIndexRoute: MobileIndexRoute,
}

const MobileRouteRouteWithChildren = MobileRouteRoute._addFileChildren(
  MobileRouteRouteChildren,
)

interface WebAuthenticatedRouteChildren {
  WebAuthenticatedBookingsRoute: typeof WebAuthenticatedBookingsRoute
  WebAuthenticatedCalendarRoute: typeof WebAuthenticatedCalendarRoute
  WebAuthenticatedDashboardRoute: typeof WebAuthenticatedDashboardRoute
  WebAuthenticatedCustomersIdRoute: typeof WebAuthenticatedCustomersIdRoute
  WebAuthenticatedCustomersIndexRoute: typeof WebAuthenticatedCustomersIndexRoute
}

const WebAuthenticatedRouteChildren: WebAuthenticatedRouteChildren = {
  WebAuthenticatedBookingsRoute: WebAuthenticatedBookingsRoute,
  WebAuthenticatedCalendarRoute: WebAuthenticatedCalendarRoute,
  WebAuthenticatedDashboardRoute: WebAuthenticatedDashboardRoute,
  WebAuthenticatedCustomersIdRoute: WebAuthenticatedCustomersIdRoute,
  WebAuthenticatedCustomersIndexRoute: WebAuthenticatedCustomersIndexRoute,
}

const WebAuthenticatedRouteWithChildren =
  WebAuthenticatedRoute._addFileChildren(WebAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MobileRouteRoute: MobileRouteRouteWithChildren,
  WebAuthenticatedRoute: WebAuthenticatedRouteWithChildren,
  WebIndexRoute: WebIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
